# permissions for end users to edit chronoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chrono-scaler
    app.kubernetes.io/managed-by: kustomize
  name: chronoscaler-editor-role
rules:
- apiGroups:
  - api.zszazi.github.io
  resources:
  - chronoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.zszazi.github.io
  resources:
  - chronoscalers/status
  verbs:
  - get
